  - name: Config mesos cluster properties
    shell: IP_PUBLIC="$(curl http://169.254.169.254/latest/meta-data/local-ipv4)"  && echo $IP_PUBLIC | sudo tee /etc/mesos-master/ip && cp /etc/mesos-master/ip /etc/mesos-master/hostname && echo MyCluster| sudo tee /etc/mesos-master/cluster
  